import WebSocket from 'ws';
import { writeFileSync } from 'fs';
const TARGET = process.argv[2];
const OUT = process.argv[3];
const Y = parseInt(process.argv[4] || '0');
const H = parseInt(process.argv[5] || '900');
const list = await (await fetch('http://localhost:9222/json/list')).json();
let tab = list.find(t => t.type === 'page');
const ws = new WebSocket(tab.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
const send = (m, p={}) => new Promise(r => { const i = ++id; pending.set(i, r); ws.send(JSON.stringify({id:i, method:m, params:p})); });
ws.on('message', d => { const m = JSON.parse(d); if (m.id && pending.has(m.id)) { pending.get(m.id)(m.result); pending.delete(m.id); } });
await new Promise(r => ws.on('open', r));
await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 5000, deviceScaleFactor: 2, mobile: false });
await send('Page.navigate', { url: TARGET });
await new Promise(r => setTimeout(r, 4500));
const { data } = await send('Page.captureScreenshot', { format: 'png', clip: { x: 0, y: Y, width: 1440, height: H, scale: 1 } });
writeFileSync(OUT, Buffer.from(data, 'base64'));
console.log('OK ->', OUT);
ws.close(); process.exit(0);
